import { Application } from "./application.model";
import { AbandonCallHistory } from "./widgets/abandonCallHistory.model";
import { AgentAOPsStatus, AgentStatus, AgentSummary, AgentSummaryChannelWise, TotalAgents } from "./widgets/agent.model";
import { AverageHandleSummary, AverageHandleSummaryLive, AverageSpeedOfAnswer } from "./widgets/avg.model";
import { CallAverageSummary, CallStatus, CallSummary, CallSummaryCampaignWise, CallSummaryInbound, CallSummaryProjectWise, CallSummaryQueueWise, CallTypeSummary, ConnectedCallVolumeTrend, InboundCallOverview, InboundCallStatistics, QueueCallSummary, SLA, TotalCalls, TotalCustomers } from "./widgets/call.model";
import { CampaignDispositionSummary, CampaignSessionSummary, CampaignStatus, CampaignSummary } from "./widgets/campaign.model";
import { ChatStatus, ChatSummary } from "./widgets/chat.model";
import { ContactListStatus } from "./widgets/contactList.model";
import { UserDispositionSummary, UserDispositionGrid, SysDispositionSummary } from "./widgets/disposition.model";
import { EmailStatus, EmailSummary } from "./widgets/email.model";
import { MessageBlaster } from "./widgets/messageBlaster.model";
import { QueueAgentStatus, QueueInteractionStatus, QueueStatus } from "./widgets/queue.model";
import { RateMeter } from "./widgets/rateMeter.model";
import { RealtimeSentiment } from "./widgets/realtimeSentiment.model";
import { SocialStatus, SocialSummary } from "./widgets/social.model";
import { TeamStatus } from "./widgets/team.model";
import { VideoStatus, VideoSummary } from "./widgets/video.model";
import { VisitStatus, VisitSummary } from "./widgets/visit.model";
import { WebFormStatus, WebFormSummary } from "./widgets/webform.model";

export class Property {
    application!: Application;
    abandonCallHistory!: AbandonCallHistory;
    campaignStatus!: CampaignStatus;
    campaignSummary!: CampaignSummary;
    agentStatus!: AgentStatus;
    agentAOPsStatus!: AgentAOPsStatus;
    teamStatus!: TeamStatus;
    agentSummary!: AgentSummary;
    agentSummaryChannelWise!: AgentSummaryChannelWise;
    callStatus!: CallStatus;
    callSummary!: CallSummary;
    chatStatus!: ChatStatus;
    chatSummary!: ChatSummary;
    emailStatus!: EmailStatus;
    emailSummary!: EmailSummary;
    videoStatus!: VideoStatus;
    videoSummary!: VideoSummary;
    socialStatus!: SocialStatus;
    socialSummary!: SocialSummary;
    queueStatus!: QueueStatus;
    queueAgentStatus!: QueueAgentStatus;
    queueInteractionStatus!: QueueInteractionStatus;
    rateMeter!: RateMeter;
    messageBlaster!: MessageBlaster;
    contactListStatus!: ContactListStatus;
    realtimeSentiment!: RealtimeSentiment;
    callSummaryCampaignWise!: CallSummaryCampaignWise;
    callSummaryQueueWise!: CallSummaryQueueWise;
    callSummaryProjectWise!: CallSummaryProjectWise;
    callSummaryInbound!: CallSummaryInbound;
    campaignSessionSummary!: CampaignSessionSummary;
    campaignDispositionSummary!: CampaignDispositionSummary;
    averageHandleSummary!: AverageHandleSummary;
    averageHandleSummaryLive!: AverageHandleSummaryLive;
    averageSpeedOfAnswer!: AverageSpeedOfAnswer;
    callAverageSummary!: CallAverageSummary;
    callTypeSummary!: CallTypeSummary;
    connectedCallVolumeTrend!: ConnectedCallVolumeTrend;
    queueCallSummary!: QueueCallSummary;
    inboundCallOverview!: InboundCallOverview;
    inboundCallStatistics!: InboundCallStatistics;
    totalCalls!: TotalCalls;
    totalAgents!: TotalAgents;
    totalCustomers!: TotalCustomers;
    userDispositionSummary!: UserDispositionSummary;
    userDispositionGrid!: UserDispositionGrid;
    sysDispositionSummary!: SysDispositionSummary;

    visitStatus!: VisitStatus;
    visitSummary!: VisitSummary;
    webFormStatus!: WebFormStatus;
    webFormSummary!: WebFormSummary;
    sla!: SLA;
}