export enum WIDGET {
    AbandonCallHistory = 'abandoncallhistory',
    CampaignStatus = 'campaignstatus',
    CampaignSummary = 'campaignsummary',
    CampaignSessionSummary = 'campaignsessionsummary',
    UserDispositionSummary = 'userdispositionsummary',
    UserDispositionGrid = 'userdispositiongrid',
    SysDispositionSummary = 'sysdispositionsummary',
    AgentStatus = 'agentstatus',
    AgentAOPsStatus = 'agentaopsstatus',
    TeamStatus = 'teamstatus',
    AgentSummary = 'agentsummary',
    AgentSummaryChannelWise = 'agentsummarychannelwise',
    CallStatus = 'callstatus',
    CallSummary = 'callsummary',
    CallTypeSummary = 'calltypesummary',
    CallSummaryStateWise = 'callsummarystatewise',
    CallAverageSummary = 'callaveragesummary',
    ChatStatus = 'chatstatus',
    ChatSummary = 'chatsummary',
    ChatSummaryStateWise = 'chatsummarystatewise',
    EmailStatus = 'emailstatus',
    EmailSummary = 'emailsummary',
    EmailSummaryStateWise = 'emailsummarystatewise',
    VideoStatus = 'videostatus',
    VideoSummary = 'videosummary',
    SocialStatus = 'socialstatus',
    SocialSummary = 'socialsummary',
    QueueStatus = 'queuestatus',
    QueueAgentStatus = 'queueagentstatus',
    QueueInteractionStatus = 'queueinteractionstatus',
    RateMeter = 'ratemeter',
    ContactListStatus = 'contactliststatus',
    MessageBlaster = 'messageblaster',
    RealtimeSentiment = 'realtimesentiment',
    CallSummaryCampaignWise = 'callsummarycampaignwise', // for Gulfsotheby
    CallSummaryQueueWise = 'callsummaryqueuewise', // for Gulfsotheby
    CallSummaryProjectWise = 'callsummaryprojectwise', // for Gulfsotheby
    CallSummaryInbound = 'callsummaryinbound', // for Gulfsotheby
    QueueCallSummary = 'queuecallsummary', // for ZANACO
    InboundCallOverview = 'inboundcalloverview', // for ZANACO (Connected Calls + Abandoned Calls)
    InboundCallStatistics = 'inboundcallstatistics', // for ZANACO (Connected Calls + Abandoned on IVR Calls + Abandoned on ACD Calls)
    AverageHandleSummary = 'averagehandlesummary', // for ZANACO
    AverageHandleSummaryLive = 'averagehandlesummarylive',
    AverageSpeedOfAnswer = 'averagespeedofanswer', // for ZANACO
    ConnectedCallVolumeTrend = 'connectedcallvolumetrend', // for ZANACO
    TotalCalls = 'totalcalls', // for ZANACO
    TotalAgents = 'totalagents', // for ZANACO
    TotalCustomers = 'totalcustomers', // for ZANACO
    Tenants = 'tenants',
    VisitStatus = 'visitstatus',
    VisitSummary = 'visitsummary',
    WebFormStatus = 'webformstatus',
    WebFormSummary = 'webformsummary',
    Leads = 'leads', // Cytecare
    SLA = 'sla', // Zanaco
}